### ISSUE TITLE
vscodium support?

### ISSUE THREAD

**Issue by Shadowblitz16** [Prince781/vala-vscode#11] opened 2020-11-09 03:54 UTC

**Comment by benwaffle** [comment] 2020-11-09 05:01
@Prince781 did you upload the extension to openvsx?

**Comment by Prince781** [comment] 2020-11-09 06:21
@benwaffle no, I haven't yet...

**Comment by benwaffle** [comment] 2021-04-24 05:52
duplicate of #9

**Closed by benwaffle** 2021-04-24 05:52 UTC
